language: node_js
node_js:
- 10.13.0
services:
- postgresql
install:
- npm install ci
- npm install pg
before script:
- npm generate-keys
- createdb onesg
script:
- npm run start
branches:
  only:
  - on-68-herokudeploy
deploy:
  provider: heroku
  api_key:
    secure: ruidJGFkZAzd9T3NM/dfdYaTh+j9kEdTwVQFBKMPz9TymfonRblJ5WIefj4fCcYJgfWl7LP/RJ79u6mu78y5rpZAvgPZV4lDjACVhnHx7u9Ss8snhLjYI5D/Im08NTqB959lZZVEuMPFKAnGZ/kxSdcX40pArnMB7ZYpA/wiv1bHe5u6BhRtPPIRBtbIrtc9OiDdyU8MxVA5tH7p8uuWafaaqbr37XU4KrN0uUx5IHTNLnQROU2JKNZlIk4pKIGBdYFSnHU/JzO8WQxO2EksE1z06gPb4o/wQfLz+qL7T5C4VlF32manpZ4573QIgE56mwpZdmTHGEKfabqaVft1GrLB+JgF0rnrhNerFSl/2tLIuZg6Wlo0j58DqBsfVMQlXKJ/8F+AJoFz9KMAHoc/u4d9pyY/yYWiOW1j21qze6M1kfeTdp7801xvoGQg7whnatWx5Wg9HkcXTUleT0oeTdrKkcNF2RHnqegwnmMyp5qOSSxA44R6ph9ZwaRttCQMysxXbe+z11Vmm4JvueGh0hLe/LSNB/cnQ9V4G+N3UpxEUx6fQztHQ+A02FeqmDcVRVS+eQRiB1WOYTutzmUXrPOxEo/iNJnnw2qi2bnwhvwi0J7Wh8Fsdo8/M4Gx6QLiifqTLsIK/qikOz45UwRH06pzlLPslulspTIGIsdX6ko=
  app:
    develop: one-sg-backend
