language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm run dev
branches:
  only:
  - develop
  - on-68-herokudeploy
deploy:
  provider: heroku
  api_key:
    secure: "F0zEZbDKXg3UVFR6KE1Bf3jLX+DPACtZA05ku5QkOadBCQZHFYRFGDjrT5/RflHJPVO0GDsnAIl77Ho+uGWgHxHxGZqnjBEdPWqw94R4bcWOd9lEHis1Q9+S5Dcuf4exorgwJvgai5VevCo6+FcEpQEgveJ/xDmrU8WEOJnlyrNzpRFU2FDAlAQvuGs+pudY76uxSrB9pvSnnYtRxBo+8fgEtOjq9l7CJdBbcbeQYMlNEmK9BJctNA8lhk3HX+zn9D9Ze9jiGSG1neINJlEIe7ufJRouJuk8qfTXnsTbxgzZKfGbGlsv11PVtNa6v9v1XXcBkcP5DbVtkvaYqFm6g8uWgMoPj28JMyMbQViGUuVBroMaljdBYNoZWUVYg4my43acDFDuMab90emHuAbOIzZLjk8aiMeBkpyo0tM9TuNK/qBi55aWdG1OjqoVj6hZraabyPohZtR+uoUfKvs9oJp1WzdnM3wFqHyOb6KICy6BwhZaO855pAm1EG62wDGvSeu7cj5OBeOagJGvKX+zvqbXGtUvq0qYBp1mdETIWdphR5j7PdX1t6BiUdYJ7yvcAVB1CDsx4FAvEieS5knk44IX/Td+jsm7ytR0Z4nFPsGJ2GXyaGWFb4Sbp0o9LyyZ+eB0GJUpsdjEB7nB2aXZYpll91PUh3pcnpQXZnPrc94="
  app:
    develop: one-sg-backend


