language: node_js
node_js:
- 10.13.0
env:
- NODE_TLS_REJECT_UNAUTHORIZED=‘0’
services:
- postgresql
install:
- npm install ci
script:
- npm run generate-keys
- npm run start
branches:
  only:
  - on-68-herokudeploy
deploy:
  provider: heroku
  api_key:
    secure: HLT4K0nc0QudmIncOnacm4ZDko5ZYmOcE6xrtqKzxP56Gq+srYuN8xmFfJ8DcK7Wej3KkQInkZ3kRoOzZDR1lPgMVWUTt6HYBOtbiRBaeHmEhulSJR2vrDDKTnQ+yyg8leavYSu+7bwwKIRdkB2NpHTHb/pfO9rIc5EmYz3cqbfi7tdbrVRcNMjm/z2rJHclyaPMhFS1qiZcbJSuYzvxLoEhMjpbGQNhZBx7sExRHfeEXt4hbs/JTdyW4b0ev0vbRx7E+RG2iuDVrv1aMcM2G91/8Txtw1m89UWyygBTwG+NjPzDlYh7CIv2z7sOoCWvN3oz5bjQggSlFgPGXC7z6cWzJzklf4DUfw9SKgvNXlSw3zea840ALtgeVndcZkyNsJKqEiv0LKuSZpiXw47XhSXuZ66jt2QT3x+FJIwJeHKEL4tzdV9+cb2HG9CzFCERFlYrCGQgttUB3cAu+OdF/4WJYTgQ2ieuOLgnZBT6XYEehpuxe35zxIgYF4oEUuzhdB9hnNnuTryH1RYxlcpLS+f5Aozup9OFSqkpCAo8i9MMgHGsvsYO2088PNo9fv8eTjyA9UkLVR3qkid5YO7zA/NsWicl/0/sFK90Uj3ylrBky6mD4NezVKAeiWFkSfB3f6dMmsIEAiAx246jZk/hOv7Yyd62jIl6qn2whaEL0ho=
  app:
    develop: one-sg-backend
