const { tableCase } = require('../src/models/case');

exports.seed = function seedCaseTable(knex) {
  // Deletes ALL existing entries
  return knex(tableCase)
    .del()
    .then(function insertCases() {
      // Inserts seed entries
      return knex(tableCase).insert([
        {
          caseNumber: 'EF2020-11001',
          caseStatus: 'NEW',
          appliedOn: '2020-11-01', // YYYY-MM-DD
          pointOfContact: 'Adam Goh',
          referenceStatus: 'UNVERIFIED',
          amountRequested: '350.55',
          amountGranted: '350',
          refereeId: 1,
          beneficiaryId: 1,
          createdBy: 1,
          updatedBy: 1,
        },
        {
          caseNumber: 'EF2020-11002',
          caseStatus: 'CLOSED',
          appliedOn: '2020-11-01',
          pointOfContact: 'Serene',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 2,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11003',
          caseStatus: 'CLOSED',
          appliedOn: '2020-11-01',
          pointOfContact: 'Hafidz',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 2,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11004',
          caseStatus: 'CLOSED',
          appliedOn: '2020-11-01',
          pointOfContact: 'Mannan',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11005',
          caseStatus: 'PENDING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Daniel',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 1,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11006',
          caseStatus: 'NEW',
          appliedOn: '2020-11-01',
          pointOfContact: 'Melissa',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 2,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11007',
          caseStatus: 'PROCESSING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Satrun',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 4,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11008',
          caseStatus: 'PENDING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Lynette',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11009',
          caseStatus: 'PROCESSING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Andrea',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 4,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11010',
          caseStatus: 'PROCESSING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Simon',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11011',
          caseStatus: 'NEW',
          appliedOn: '2020-11-01',
          pointOfContact: 'Taufik',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11012',
          caseStatus: 'PROCESSING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Stegosaurus',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 4,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11013',
          caseStatus: 'REFERRED',
          appliedOn: '2020-11-01',
          pointOfContact: 'Halimah',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11014',
          caseStatus: 'PROCESSING',
          appliedOn: '2020-11-01',
          pointOfContact: 'Ryder',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '375.50',
          amountGranted: '0',
          beneficiaryId: 3,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11015',
          caseStatus: 'CLOSED',
          appliedOn: '2020-11-01',
          pointOfContact: 'Rocky',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary found a job',
          amountRequested: '182.50',
          amountGranted: '0',
          beneficiaryId: 4,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11016',
          caseStatus: 'NEW',
          appliedOn: '2020-11-01',
          pointOfContact: 'Pikachu',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary went overseas',
          amountRequested: '600.00',
          amountGranted: '0',
          beneficiaryId: 1,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11017',
          caseStatus: 'NEW',
          appliedOn: '2020-10-31',
          pointOfContact: 'Starshea',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary uncontactable',
          amountRequested: '175.50',
          amountGranted: '100.00',
          beneficiaryId: 2,
          createdBy: 2,
          updatedBy: 2,
        },
        {
          caseNumber: 'EF2020-11018',
          caseStatus: 'REFERRED',
          appliedOn: '2020-12-01',
          pointOfContact: 'Janice',
          referenceStatus: 'PENDING',
          casePendingReason: 'Beneficiary contacted but declined',
          amountRequested: '200.50',
          amountGranted: '0',
          beneficiaryId: 1,
          createdBy: 2,
          updatedBy: 2,
        },
      ]);
    });
};
